[package]
name = "spl"
version = "0.1.7"
edition = "2021"
description = "Stack Pogramming Language: A simple, concise scripting language."
license = "MIT"
repository = "https://github.com/tudbut/spl"
authors = ["TudbuT"]

[dependencies]
readformat = "0.1"
once_cell = "1.17"
multicall = "0.1.4"
